#!/usr/bin/env sh

crystal tool format -e lib -e ./spec_bench/support/neural_network/data/patterns_with_base_noise.cr -e ./spec_bench/support/neural_network/data/patterns_with_noise.cr -e ./spec_bench/support/neural_network/data/training_patterns.cr